name: Build and Push Docker Images

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch (modify if needed)
  schedule:
    # Run the job every Sunday at 00:00 UTC
    - cron: "0 0 * * 0"
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        base_image:
          - python:3.12

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub using a Personal Access Token
      - name: Log in to Docker Hub with PAT
        env:
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        run: echo "${DOCKER_PAT}" | docker login -u glitchassassin --password-stdin

      # Build the Docker image with the base image as a build argument
      - name: Build the Docker image
        run: |
          # Extract tag from the base image
          TAG=$(echo "${{ matrix.base_image }}" | tr -d '.:' | tr - _)
          docker build --build-arg BASE_IMAGE=${{ matrix.base_image }} --platform linux/amd64,linux/arm64 -t glitchassassin/devcontainer:${TAG} .

      # Push the Docker image to the registry
      - name: Push the Docker image
        run: |
          TAG=$(echo "${{ matrix.base_image }}" | tr -d '.:' | tr - _)
          docker push glitchassassin/devcontainer:${TAG}
